name: oriva_app_client
description: "Oriva — Marketplace mobile premium. App cliente pour découvrir et acheter."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Typography
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  lucide_icons_flutter: ^3.0.5

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Routing
  go_router: ^14.6.2

  # Supabase
  supabase_flutter: ^2.8.0

  # Storage & session
  shared_preferences: ^2.3.3

  # Images
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0

  # Utils
  intl: ^0.19.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true
  assets:
    - .env
